// This function plays an animation generated by convgif.py in lib\FacialSprites
// offset_x - The x position offset of our animation
// offset_y - The y position offset of our animation
// animation - This is the animation variable generated by convgif. It is the filename of the .gif file inputted into convgif.py
// overlay - This determines whether or not to overlay the next frame ontop of the previous frame. Usually you want to set it to true unless you have smaller frames
//-----------------------------------------------------------------------
// Inside the Animation class are 3 variables:
// numFrames - how many frames there are in total (also the array lengths)
// animation - the pointer array to each frame
// frameTimes - an array containing times in ms to keep the frame for.
// All these values are automatically filled for you via convgif.py
void playAnimation(int offset_x, int offset_y, Animation animation, bool overlay)
{
    for (int i = 0; i < animation.numFrames; i++)
    {
        drawFace(offset_x, offset_y, animation.animation[i], overlay, true);
        waitInterruptable(animation.frameTimes[i]);
    };
}
